// Dev config - Do not commit!
module.exports = {
  STRAPI_URI: process.env.STRAPI_URI,
  STRAPI_USERNAME: process.env.STRAPI_USERNAME,
  STRAPI_PASSWORD: process.env.STRAPI_PASSSWORD,
  YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY,
  SOUNDCLOUD_CLIENT_ID: process.env.SOUNDCLOUD_CLIENT_ID,
  SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET
}
